### ISSUE TITLE
Download only on wifi

### ISSUE THREAD

**Issue by oXidFoX** [mikepenz/wallsplash-android#16]
context: used with Muzei.
Could you add an option to download picture only on Wifi ? It will be usefull for people without unlimited data plan.
Or (I don't know if it's possible) something like a cache if you can't choose when Muzei "request" a new picture.

**Comment by mikepenz** [comment]
@oXidFoX thanks for the idea. i'll try to improve the muzei integration in one of the future updates.

**Comment by oXidFoX** [comment]
oh it seems an issue is already open in Muzei : https://github.com/romannurik/muzei/issues/59

**Comment by mikepenz** [comment]
This is in the latest play store version ;)
