### ISSUE TITLE
Update the github project

### ISSUE THREAD

**Issue by DavidPacioianu** [mikepenz/wallsplash-android#20]
Could you please update the code available on github? I saw some interesting things in the latest version available in Google Play.

Thank you very much for sharing this awesome app with us.

**Comment by DominikAngerer** [comment]
Hey @DavidPacioianu as announced here: https://twitter.com/wallsplashapp/status/595998392637124609 we're no longer updating this repository with the new features of wallsplash. We hope you still like our app - new features will come soon.

BR,
Dominik
