### ISSUE TITLE
Picasso Palette Helper 

### ISSUE THREAD

**Issue by danielgomezrico** [mikepenz/wallsplash-android#22]
Hi

I just wanted to suggest https://github.com/florent37/PicassoPalette for the palette, it´s simple and do a great job with cache.

**Comment by mikepenz** [comment]
@danielgomezrico no external libraries regarding things which are already available by default. 
We also use the normal `Palette` from the `CompatLibrary` which is working great. We also use our own cache.

**Comment by danielgomezrico** [comment]
But he uses `android.support.v7.graphics.Palette`.

**Comment by mikepenz** [comment]
@danielgomezrico me too. so i see no advantage.

**Comment by danielgomezrico** [comment]
:+1:
