### ISSUE TITLE
2.1 Version

### ISSUE THREAD

**Issue by danielgomezrico** [mikepenz/wallsplash-android#23]
Hi

Where is the code for the 2.1 version?

**Comment by mikepenz** [comment]
@danielgomezrico sorry. Starting with v2.0.0, all new features and changes are closed source. There were to many people simply reusing it and stating it as their own. I have decided that the current public base is very very stable and one of the most complete sample applications up on GitHub.

I will still add Pull Requests here if someone else wants to provide some of his knowledge. 

Thanks for your interest. 

Here's the statement @Twitter
https://twitter.com/wallsplashapp/status/595998392637124609

**Comment by danielgomezrico** [comment]
:(

**Comment by mikepenz** [comment]
@danielgomezrico the public source is already to good to be open source. :P

**Comment by danielgomezrico** [comment]
but why let it good if it can be GREAT?

**Comment by mikepenz** [comment]
@danielgomezrico the closed source is not only GREAT but AWESOME :P

**Comment by danielgomezrico** [comment]
so share that AWESOME so everything can became AWESOMEEEEEEEEE :+1:

**Comment by mikepenz** [comment]
No sorry :D

I already shared so much knowledge. Also with all my other libraries. Something should stay my personal  :P

**Comment by danielgomezrico** [comment]
or... create a blog, it´s another way to share knowledge

**Comment by danielgomezrico** [comment]
but... if you share something great more people will share more great stuff... and you will gona learn from others too, like my suggestion to use Picasso palette, or others more useful...
