### ISSUE TITLE
Issue with com.android.support:design:22.2.0

### ISSUE THREAD

**Issue by matthew2402** [mikepenz/wallsplash-android#24]
There's an issue with the new support design library

- "Error:(1) Attribute "insetForeground" has already been defined"

**Comment by mikepenz** [comment]
@matthew2402 that's because they now included the InsetsFrameLayout into the design lib. It is internal so i can't use it. i will rename the insetForeground in the MaterialDrawer with the next update

**Comment by mikepenz** [comment]
@matthew2402 ok sorry. this is no issue of the MaterialDrawer as i've prefixed this attribute. please check other libraries you use.

**Comment by mikepenz** [comment]
@matthew2402 any library which is in use will have this attribute set. The source as is hasn't this issue.
