### ISSUE TITLE
unsplash api

### ISSUE THREAD

**Issue by mingqlin** [mikepenz/wallsplash-android#25]
Is unsplash api is public, when run the app with end point: 

public static final String ENDPOINT = "http://wallsplash.lanora.io";

it asks to upgrade.

current version wallsplash  seem to use end point: http://**

just wondering if these api are public for everyone to use? if so, there are they document about the api

**Comment by mikepenz** [comment]
@mingqlin as the api states it is not public to use. 

As this repo states the api was never public nor free. https://github.com/mikepenz/wallsplash-android#restrictions
