### ISSUE TITLE
Do you have tutorial How create favorite button

### ISSUE THREAD

**Issue by helmifluida** [mikepenz/wallsplash-android#26]
Hay master how to create favorite button in recyclerView and save data to FavoriteFragment ?? I want this tutorial
Thanks mikepenz

**Comment by mikepenz** [comment]
@helmifluida this project is meant to showcase some core Android functionalities packed in an performant, super fast application. The whole thing is meant for experiences programmers as a showcase how specific things can be implemented. 

The source is and will stay as given. 

Please also note the restrictions:
https://github.com/mikepenz/wallsplash-android#restrictions

And the license:
https://github.com/mikepenz/wallsplash-android#license
