### ISSUE TITLE
Standalone live wallpaper

### ISSUE THREAD

**Issue by xasx** [mikepenz/wallsplash-android#28]
I'd love to have live wallpapers without having to use Muzei.

Is it possible to provide this? Do other users want this?

During research I stumbled upon this:
[Android Live Wallpaper - Tutorial](http://www.vogella.com/tutorials/AndroidLiveWallpaper/article.html)

**Comment by mikepenz** [comment]
Not planned at the moment. But I'm open for PRs ;)
