### ISSUE TITLE
How you are doing with the loved images ?

### ISSUE THREAD

**Issue by addelll** [mikepenz/wallsplash-android#32]
ok so from 2.0.0 there is no more update just tell me how you do with loved image and the ripple effect for it .
thanks .

**Comment by mikepenz** [comment]
The `ImageListActivity` of the `FastAdapter` has the same effect:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/ImageListActivity.java

**Comment by addelll** [comment]
I'm not using FastAdapter and I dont find it in source ???

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/ImageListActivity.java#L95
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/ImageItem.java

**Comment by addelll** [comment]
Thanks .
