### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [mikepenz/wallsplash-android#36]
Hi,

Thanks for this app, one of the most beautiful I have ever seen :)

Have you planned to put this application on F-Droid? I can give you some links with documentation if you want

**Comment by mikepenz** [comment]
@Poussinou hi. Thank you very much :). 

Sadly not. And I have no plans to do so at the moment. (Note v2 of wall:splash was not open sourced anymore. the source-code here is of v1)

**Comment by Poussinou** [comment]
OK, no problem;) if you have the time maybe one day... But that's OK:)
Thanks again
