### ISSUE TITLE
Abt Account Header Dropdown code

### ISSUE THREAD

**Issue by rohitlanjewar009** [mikepenz/wallsplash-android#38]
I wanted to show view like attached image on dropdown of account header.
So I needed code for dropdown of AccountHeader in NavigationDrawer for my application. Please help me to resolve my issue as early as possible.
![screenshot_2017-11-02-13-22-10](https://user-images.githubusercontent.com/30696478/32315528-6b2e9096-bfd2-11e7-9eb4-6d70e870b6e6.png)

**Comment by mikepenz** [comment]
@rohitlanjewar009  head over to the `MaterialDrawer` library

**Comment by rohitlanjewar009** [comment]
@rohitlanjewar009 head over to the MaterialDrawer library
Sir I didnot get it. Please send me the code which gives output like image as shown above
![screenshot_2017-11-02-13-22-10](https://user-images.githubusercontent.com/30696478/32317226-19bd1d66-bfd9-11e7-8b31-b91a30b5ea39.png)

**Comment by mikepenz** [comment]
Everything is in this repo + also in the `MaterialDrawer` library

**Comment by rohitlanjewar009** [comment]
Ok Thanks Sir! Thank you Sir for your Fast reply.
