### ISSUE TITLE
Wallpapers Never Load Despite Having Connection on Wallsplash

### ISSUE THREAD

**Issue by idimummy** [mikepenz/wallsplash-android#39]
#### Expected behavior
App should load wall papers.

#### Actual behavior
Application loads and after some time shows no connection retry.

#### How to reproduce
Download Wallsplash (v3.2.5) from play store [here](https://play.google.com/store/apps/details?id=com.mikepenz.unsplash), launch it and wait for it to load wallpapers .

* Operating system:Android Version 7.0  
* Device used: Tecno Boom J8

#### Recording Of The Bug
https://youtu.be/lFiTNVZsDfw
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kennykajo/bug-report-on-wallsplash">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mikepenz** [comment]
@idimummy as mentioned on the play store. the app is discontinued. no further adjustments will be made. nor will there be any further development on the open source code. thank you
